/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_0.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_1.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_2.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_3.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_4.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_5.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_6.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_7.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_8.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_9.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_10.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_11.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_12.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_13.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_14.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_15.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_16.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_17.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_18.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_19.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_20.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_21.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_22.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_23.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_24.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_25.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_26.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_27.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_28.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_29.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_30.sh & 
/home/fwillett/handwritingBCIData/RNNTrainingSteps/bashScratch/lmDecode_31.sh & 
